# Generated by Django 3.0.3 on 2020-02-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdetail',
            name='department',
            field=models.CharField(max_length=1),
        ),
    ]
